### ISSUE TITLE
boot process

### ISSUE THREAD

**Issue by KwangSon** [sipeed/LicheePi4A#12]
Hi, I want to know early boot process after rom.

https://wiki.sipeed.com/hardware/en/lichee/th1520/lpi4a/7_develop.html#U-boot

I can find rom -> uboot spl.
which adress of  spl should placed?(how rom read spl? file name? or just chunk of address?)

i've tested with prebuilt uboot load same uboot image again.(for make sure it works.)
 
```
ext4load mmc 1:1 0x1c00000 u-boot-with-spl.bin
go 0x1c00000
```
it just hang after `## Starting application at 0x01C00000 ...`

**Comment by dtometzki** [comment]
Hello KwangSon,

perhaps you will find here all the iformation what do you need: ?
https://gitee.com/thead-yocto/u-boot/blob/master/include/configs/light-c910.h

At line 425 you find the info for licheepi4a

**Comment by KwangSon** [comment]
> Hello KwangSon,
> 
> perhaps you will find here all the iformation what do you need: ? https://gitee.com/thead-yocto/u-boot/blob/master/include/configs/light-c910.h
> 
> At line 425 you find the info for licheepi4a

Hi, thanks for comment.
More detail, I want to know how `brom` load uboot image(emmc) to ram, because I'm try to upstream uboot. :)
This is only vendor can know.

**Comment by orangecms** [comment]
Hi, some people from Sipeed (IIUC) are working on upstreaming; first patches just occurred in the U-Boot mailing list:
https://lists.denx.de/pipermail/u-boot/2023-May/518879.html

From what I understand, the TH1520 implements the Android fastboot thing in the mask ROM.
I keep asking for a SoC manual. Hope we'll get one at some point.

Hope that helps a bit. :)

**Comment by KwangSon** [comment]
> Hi, some people from Sipeed (IIUC) are working on upstreaming; first patches just occurred in the U-Boot mailing list: https://lists.denx.de/pipermail/u-boot/2023-May/518879.html
> 
> From what I understand, the TH1520 implements the Android fastboot thing in the mask ROM. I keep asking for a SoC manual. Hope we'll get one at some point.
> 
> Hope that helps a bit. :)

Great! thanks, it helped.
