### ISSUE TITLE
Missing TH1520 SOC documentation

### ISSUE THREAD

**Issue by AKeen12344** [sipeed/LicheePi4A#17]
There's basically no publicly available information about any part of this SOC, except maybe the GPU model used and that's not really useful either. Only real place where any parts of the SOC are documented in any detail are hidden in THead's Yocto Gitee repository.

**Comment by Kreyren** [comment]
+1 Cross-referencing from Beagle forum https://forum.beagleboard.org/t/docs-for-th1520/35860

**Comment by KwangSon** [comment]
@AKeen12344 
https://lore.kernel.org/linux-riscv/ZMME6cHQzHMLUCq+@x1/#t
Drew already asked to t-head about datasheet but seems takes time.

@Kreyren if you want soc chip layout then contact to beagleboard. ( I guess they opend?)

**Comment by Kreyren** [comment]
@KwangSon Contact how? forum post not enough?

**Comment by KwangSon** [comment]
> @KwangSon Contact how? forum post not enough?

I'm not sure. depends what specific information you needs.
did you check this info?
https://docs.beagleboard.org/latest/boards/beaglev/ahead/03-design.html#

**Comment by AKeen12344** [comment]
> > @KwangSon Contact how? forum post not enough?
> 
> I'm not sure. depends what specific information you needs. did you check this info? https://docs.beagleboard.org/latest/boards/beaglev/ahead/03-design.html#

Pretty sure both of us want some more detail on hardware accelerated parts. Looking through a repo to get some level of hope of what's going on is not the greatest.

Last time I checked, both vendors were a little cagey just disclosing what GPU powers the TH1520.

(Please excuse the newbie marks)

**Comment by Kreyren** [comment]
> @Kreyren if you want soc chip layout then contact to beagleboard. ( I guess they opend?) -- @KwangSon (https://github.com/sipeed/LicheePi4A/issues/17#issuecomment-1709536426)

Didn't know that exists, thanks! that's very helpful

**Comment by AKeen12344** [comment]
TH1520 docs are up on https://git.beagleboard.org/beaglev-ahead/beaglev-ahead/-/tree/main/docs?ref_type=heads

Beagle were in the process of going through what they can disclose via their repo at the time the other comments talking about asking them, which kind of bugged me quite a bit for other reasons, but looks THead Semi did it themselves and Beagle mirrored it on their own repos.

This documentation is not available on the English version of THead's website as far as I can tell, and they have a login requirement to download.

**Comment by Kreyren** [comment]
cool, thanks

-- Jacob "Kreyren" Hrbek

------- Original Message -------
