### ISSUE TITLE
how to connect jtag?

### ISSUE THREAD

**Issue by KwangSon** [sipeed/LicheePi4A#3]
Hi, I'm try to low level programming. (also have sipeed jtag)
how can I attach jtag to licheepi4a? I cannot find anything on wiki
Thanks!.

**Comment by Zepan** [comment]
hi ， the jtag only exposed on SOM, you can see 8 test points near eMMC.

**Comment by KwangSon** [comment]
> hi ， the jtag only exposed on SOM, you can see 8 test points near eMMC.

found. thanks. any guide to enter jtag mode?

**Comment by orangecms** [comment]
Some thoughts:

The 8 solder pads on the top of the SoM held DIP switches in earlier photos posted on Twitter.
Some combination might enable JTAG.

I would assume that it requires a probe supporting T-Head's custom protocol, similar to the D1 SoC that is based on a T-Head C906 core.
