### ISSUE TITLE
flash tools.

### ISSUE THREAD

**Issue by stolk** [sipeed/LicheePi4A#8]
The wiki [mentions](https://wiki-sipeed-com.translate.goog/hardware/en/lichee/th1520/lpi4a/4_burn_image.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) `burn_tool.zip` but has no link to it.

Where can I get the flashing tool for this board?

**Comment by stolk** [comment]
Is it the same as [fastboot](https://packages.ubuntu.com/kinetic/fastboot) from android tools?
```
$ sudo fastboot devices -l
????????????           fastboot usb:1-1
```
From system log:
```
kernel: usb 1-1: new high-speed USB device number 18 using xhci_hcd
kernel: usb 1-1: New USB device found, idVendor=2345, idProduct=7654, bcdDevice= 2.23
kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
kernel: usb 1-1: Product: USB download gadget
kernel: usb 1-1: Manufacturer: T-HEAD
mtp-probe[29190]: checking bus 1, device 18: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
mtp-probe[29190]: bus: 1, device: 18 was not an MTP device
mtp-probe[29196]: checking bus 1, device 18: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
mtp-probe[29196]: bus: 1, device: 18 was not an MTP device
```

**Comment by dtometzki** [comment]
Hello Stolk,
you can download the tools from: 
https://mega.nz/folder/phoQlBTZ#cZeQ3qZ__pDvP94PT3_bGA

You will find the link here: https://wiki.sipeed.com/hardware/en/lichee/th1520/lpi4a/3_images.html under debian. 

Damian

**Comment by LenReinhart** [comment]
It is part of the download link at the bottom of the page in the section before the mention: https://wiki.sipeed.com/hardware/en/lichee/th1520/lpi4a/3_images.html 

 

I used the Mega cloud disk link. You select the software you want and it zips up the files (mostly other zips) and then you can download the zip.

 

From: Bram Stolk ***@***.*** 
Sent: Sunday, May 21, 2023 1:47 PM
To: sipeed/LicheePi4A ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sipeed/LicheePi4A] flash tools. (Issue #8)

 

The wiki mentions <https://wiki-sipeed-com.translate.goog/hardware/en/lichee/th1520/lpi4a/4_burn_image.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp>  burn_tool.zip but has no link to it.

Where can I get the flashing tool for this board?

**Comment by stolk** [comment]
Ok, thanks. The confusion stems from the fact that it is on mega but not on the other mirror.
I thought they would be identical.
